[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
linker = "./.cargo/lld-link-winegcc"
rustflags = [
    "-Lnative=./.cargo/wine-msvc-libs",
]

[env]
CC_x86_64_pc_windows_msvc = "/usr/local/bin/winegcc --target=x86_64-windows-msvc"
CXX_x86_64_pc_windows_msvc = "/usr/local/bin/wineg++ --target=x86_64-windows-msvc"
AR_x86_64_pc_windows_msvc = "/usr/local/bin/llvm-lib"
CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_AR = "/usr/local/bin/llvm-lib"
