[build]
target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
linker = "/Users/christopher/Documents/xgameruntime-rs/.cargo/lld-link-winegcc"
rustflags = [
    "-Lnative=/Users/christopher/Documents/xgameruntime-rs/.cargo/wine-msvc-libs",
]

[env]
CC_x86_64_pc_windows_msvc = "/usr/local/bin/winegcc --target=x86_64-windows-msvc"
CXX_x86_64_pc_windows_msvc = "/usr/local/bin/wineg++ --target=x86_64-windows-msvc"
AR_x86_64_pc_windows_msvc = "/Users/christopher/Downloads/llvm-project-5e96669f06077099aa41290cdb4c5e6fa0f59349/build/bin/llvm-lib"
CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_AR = "/Users/christopher/Downloads/llvm-project-5e96669f06077099aa41290cdb4c5e6fa0f59349/build/bin/llvm-lib"
